name: hourly_taxi_demand_feature_pipeline

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:    # Allows manual execution

env:
  PYTHON_VERSION: "3.12"  

jobs:
  feature_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Execute inference pipeline script
        run: |
          source venv/bin/activate
          python -c "import sys, os; sys.path.append(os.path.join(os.getcwd(), 'src')); import src.inference_pipeline"
