name: hourly_taxi_demand_feature_pipeline

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:    # Allows manual execution

env:
  PYTHON_VERSION: "3.12"  

jobs:
  feature_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt  # Ensure dependencies are installed here

      - name: Install IPython kernel
        run: |
          source venv/bin/activate
          pip install ipykernel

      - name: Register the virtual environment as a Jupyter kernel
        run: |
          source venv/bin/activate
          python -m ipykernel install --user --name=taxi_venv --display-name "Python (taxi_venv)"

      - name: Run feature pipeline notebook
        env: 
          HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          source venv/bin/activate
          jupyter nbconvert --execute --to notebook notebooks/12_feature_pipeline.ipynb
